### PR TITLE
Edit workflow history api

### LINKED ISSUE #7: Update the workflows history API to support reviews
## Description
This task consists of modifying the workflow history API (used in #8) to support the new *Resume review* step type.

## Acceptance criteria
* The changes described by #9 are implemented
* A passing automated test verifying the behavior of the API is added to the repository.

## Dependencies
* #9

### PR DESCRIPTION
**Pull request by monal20**
pull request should close issue #7

### CODE REVIEW

**Comment by monal20** [comment]
Noticed while trying to change the api that the get request relied on information parsed from the start and validate endpoints. Thus, not many changes were made to the get endpoint, besides updating the documentation to be consistent with the output in start and validate.

**Review by Nicolapps — CHANGES_REQUESTED** [review]
Thanks for your PR! It looks like to me that your test doesn’t check the API for the workflow history of a document (`/route`), just the API that returns the details about the workflow model (`/routemodel/:id`).

To test the workflow history API, you would need to create a test document. You can see an example of how to do it in `TestRouteResource#testValidateRouteWithResumeReview`.

**Comment by monal20** [comment]
Thanks for the Code Review Nicolas! I've changed to api test to reflect route. Let me know if anything else seems off.

**Review by Nicolapps — APPROVED** [review]
Thank you for the changes! I removed the lines that create the entity manager because they are useful only if you do database requests directly inside the test.

LGTM

**Pull request merged**
